version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node
    volumes:
      - ./progetto:/home/node
    ports:
      - "8888:8888"
    expose:
      - "8888"
    command: "npm start"

  couchdb:
    image: "couchdb:1.6.1"
    expose:
      - "5984"
    volumes:
      - ./data:/usr/local/var/lib/couchdb
